require('luarocks.loader')

local downloadRequire = require('fancyrequire.download')
local compileRequire = require('fancyrequire.compile')
local withTests = downloadRequire('minitest')
local assert = downloadRequire('luassert')

withTests(function(c) 
    c:describe("buffers",function(c)
        local buffer
        c:it("require", function(c)
            buffer = compileRequire('buffer')
        end)
        c:it("create",function(c)
            assert.userdata(buffer("this is a test").self)
        end)
        c:it("equal",function(c)
            assert.equals(buffer("this is a test"),buffer("this is a test"))
            assert.is_not.equals(buffer("this is a test"),buffer("test"))
            assert.is_not.equals(buffer("this is a test"),buffer("derp is a test"))
            assert.is_not.equals(buffer("this is a test"),buffer("this is a test 2"))
        end)
        c:it("set",function(c)
            local b = buffer("this is a test")
            b:set("this is a derp")
            assert.equals(b,buffer("this is a derp"))
        end)
        c:it("concatenate",function(c)
            local a = buffer("this is ")
            local b = buffer("a test")
            assert.equals(a..b,buffer("this is a test"))
        end)
        c:it("string", function(c)
            local a = buffer("this is a test")
            assert.same("this is a test", a:string())
        end)
        c:it("clone", function(c)
            local a = buffer("this is a test");
            local b = a:clone();
            a:set("that was a test");
            assert.same("that was a test", a:string())
            assert.same("this is a test", b:string())
        end)
        c:it("consolidate", function(c)
            local buf = buffer("prefix infix suffix");
            buf = buf:slice(7,12);
            assert.same("infix",buf:string())
            buf = buf:consolidate()
            assert.same("infix",buf:string())
        end)
    end)
end)
