require('luarocks.loader')

local downloadRequire = require('fancyrequire.download')
local compileRequire = require('fancyrequire.compile')
local withTests = downloadRequire('minitest')
local assert = downloadRequire('luassert')

withTests(function(c) 
    c:describe("buffers",function(c)
        local buffer = compileRequire('buffer')
        c:it("create",function(c)
            assert.userdata(buffer("this is a test").self)
        end)
        c:it("equal",function(c)
            assert.equals(buffer("this is a test"),buffer("this is a test"))
        end)
        c:it("set",function(c)
            local b = buffer("this is a test")
            b:set("this is a derp")
            assert.equals(b,buffer("this is a derp"))
        end)
        c:it("concatenate",function(c)
            local a = buffer("this is ")
            local b = buffer("a test")
            assert.equals(a..b,buffer("this is a test"))
        end)
    end)
end)
